### ISSUE TITLE
Create a !keyword command for searching for keywords

### ISSUE THREAD

**Issue by scooper4711** [StarWarsDev/legion-discord-bot#5]
Search for a keyword using !keyword <exact name> command.
If needed, replace spaces in multi-word keywords with hyphens.

**Comment by stevegood** [comment]
This is definitely a feature I'd like to implement.  However, this may need to wait until after the archives project has been launched to avoid duplicate effort.  I'll leave this open so it can stay tracked.

**Comment by stevegood** [comment]
This has been added in #12 , the Archives rebuild.
