### ISSUE TITLE
legion-hq.com domain is going away soon

### ISSUE THREAD

**Issue by scooper4711** [StarWarsDev/legion-discord-bot#6]
From the legion-hq.com site:

> Legion-HQ will be decommissioned in late October. A link is below to the new builder. All your saved lists will be copied over the new builder.

The new URL is https://legion-hq.herokuapp.com/
I spotted references to legion-hq.com in the code when browsing.

**Comment by stevegood** [comment]
I think the heroku domain is there for development and testing.  I’ll verify with Niick to see what’s up.

**Comment by stevegood** [comment]
After speaking with Niick it looks like the domain will indeed be deprecated but not in favor of the heroku app domain.  The change is still months away.  I'll continue working with Niick to ensure that all image URLs are correct upon launch.
