### ISSUE TITLE
Create legion data service

### ISSUE THREAD

**Issue by scooper4711** [StarWarsDev/legion-discord-bot#7]
Create a service with the following endpoints (or similar). All requests require authentication. By including the gameName, this allows for supporting multiple games with the same service.
* getData(gameName, category, term): returns definition
* getTermToDefine(gameName): returns category and term which needs defining. Only when X number of distinct users submit the same definition is one accepted.
* define(gameName, category, term, definition): submits a definition for a term. Submissions from an admin are accepted as is, submissions from others must be validated by others.
* blacklist(user): if a user is determined to have submitted intentionally bad data, future requests to define a term are ignored.

**Comment by stevegood** [comment]
This work is being handled in the [archives project](https://github.com/StarWarsDev/archives).  The archives will expose a graphql API to allow for flexibility as well as future proofing.
